import { Medal, Zap, Home, Hammer, Award, TrendingUp, Briefcase } from "lucide-react";

export const LENDERS = [
  {
    id: "1",
    name: "Lender 1",
    title: "Senior Mortgage Loan Officer",
    company: "Company Name Here",
    nmls: "NMLS #000001",
    tagline: "Short tagline goes here — one memorable line.",
    shortBio: "Short bio for the card. Keep it to 1–2 sentences highlighting specialty and experience.",
    fullBio: "Full biography goes here. 2–3 paragraphs describing background, experience, approach to lending, and what makes them a great fit for military and relocation buyers in the Dayton area.",
    phone: "(555) 555-0001",
    email: "lender1@example.com",
    website: "https://example.com",
    photo: null as string | null,
    specialties: ["VA Loans", "Military Relocation", "First-Time Buyers"],
    loanTypes: [
      { label: "VA Purchase Loan",     note: "0% down, no PMI — veterans & active duty" },
      { label: "VA IRRRL Refinance",   note: "Streamlined refi for existing VA loans" },
      { label: "Conventional Loan",    note: "3–20% down, flexible terms" },
      { label: "FHA Loan",             note: "Low down payment, flexible credit" },
      { label: "Cash-Out Refinance",   note: "Access your equity for any purpose" },
    ],
    why: [
      { icon: Medal,  title: "VA Specialist",  body: "Add detail about VA loan expertise and track record with military buyers." },
      { icon: Zap,    title: "Fast Closings",  body: "Add detail about turnaround speed and pre-approval process." },
      { icon: Home,   title: "Local Expert",   body: "Add context about knowledge of the Dayton/WPAFB market." },
    ],
  },
  {
    id: "2",
    name: "Lender 2",
    title: "Mortgage Loan Officer",
    company: "Company Name Here",
    nmls: "NMLS #000002",
    tagline: "Short tagline goes here — one memorable line.",
    shortBio: "Short bio for the card. Keep it to 1–2 sentences highlighting specialty and experience.",
    fullBio: "Full biography goes here. 2–3 paragraphs describing background, experience, approach to lending, and what makes them a great fit for military and relocation buyers in the Dayton area.",
    phone: "(555) 555-0002",
    email: "lender2@example.com",
    website: "https://example.com",
    photo: null as string | null,
    specialties: ["FHA Loans", "First-Time Buyers", "Renovation Loans"],
    loanTypes: [
      { label: "FHA Loan",             note: "Low down payment, flexible credit" },
      { label: "Conventional Loan",    note: "3–20% down, competitive rates" },
      { label: "VA Purchase Loan",     note: "0% down, no PMI" },
      { label: "203k Renovation Loan", note: "Buy and renovate with one loan" },
      { label: "USDA Rural Loan",      note: "0% down for eligible Ohio properties" },
    ],
    why: [
      { icon: Home,   title: "First-Time Buyer Focus", body: "Add detail about approach to guiding first-time buyers." },
      { icon: Hammer, title: "Renovation Expert",      body: "Add context about 203k and renovation lending experience." },
      { icon: Award,  title: "Award / Credential",     body: "Add any relevant credentials, volume stats, or recognitions." },
    ],
  },
  {
    id: "3",
    name: "Lender 3",
    title: "Mortgage Loan Officer",
    company: "Company Name Here",
    nmls: "NMLS #000003",
    tagline: "Short tagline goes here — one memorable line.",
    shortBio: "Short bio for the card. Keep it to 1–2 sentences highlighting specialty and experience.",
    fullBio: "Full biography goes here. 2–3 paragraphs describing background, experience, approach to lending, and what makes them a great fit for military and relocation buyers in the Dayton area.",
    phone: "(555) 555-0003",
    email: "lender3@example.com",
    website: "https://example.com",
    photo: null as string | null,
    specialties: ["Conventional Loans", "Jumbo Loans", "Investment Property"],
    loanTypes: [
      { label: "Conventional Loan",   note: "3–20% down, competitive rates" },
      { label: "Jumbo Loan",          note: "Above conforming limits" },
      { label: "VA Purchase Loan",    note: "0% down, no PMI" },
      { label: "Investment Property", note: "1–4 unit, portfolio & DSCR options" },
      { label: "Cash-Out Refinance",  note: "Access equity for any purpose" },
    ],
    why: [
      { icon: TrendingUp, title: "Investment Specialist", body: "Add detail about experience with investment and multi-unit properties." },
      { icon: Briefcase,  title: "High-Volume Closer",    body: "Add context about closing volume and complex transactions." },
      { icon: Award,      title: "Award / Credential",    body: "Add any relevant credentials, awards, or volume stats." },
    ],
  },
];
